/*
 *  UCF COP3330 Fall 2021 Assignment 3 Solutions
 *  Copyright 2021 Thomas Wallsmith
 */

/*
 *  Exercise 25 - Password Strength Indicator
 *
 *  Create a program that determines the complexity of a given password based on these rules:
 *      - A very weak password contains only numbers and is fewer than eight characters.
 *      - A weak password contains only letters and is fewer than eight characters.
 *      - A strong password contains letters and at least one number and is at least eight characters.
 *      - A very strong password contains letters, numbers, and special characters and is at least eight characters.
 *      - If a password does not meet any of these rules, then report it as a password of unknown strength.
 *
 *  Constraints
 *      - Create a <passwordValidator> function that takes in the password as its argument and returns a numeric value
 *        you can evaluate to determine the password strength.
 *      - Use a single output statement.
 *
 *  Example Output
 *      > The password '12345' is a very weak password.
 *      > The password 'abcdef' is a weak password.
 *      > The password 'abc123xyz' is a strong password.
 *      > The password '1337h@xor!' is a very strong password.
 *
 */


package baseline;

public class Solution25 {
    public static void main(String[] args) {

        //Prompt the console for a string
        //Scan in the string

        //Call passwordValidator() and store resulting number

        //Call createOutput() to generate the output in a string
        //Print output statement

    }
    public static int passwordValidator(String string){

        /*
         *  Takes in a string and determines if it is a very weak (0), weak (1), strong (2), or very strong (3) password.
         *      - a "very weak" password contains only numbers and is fewer than eight characters.
         *      - a "weak" password contains only letters and is fewer than eight characters.
         *      - a "strong" password contains letters and at least one number and is at least eight characters.
         *      - a "very strong" password contains letters, numbers, and special characters and is at least
         *        eight characters.
         */

        //If the string contains only numbers and is >8 characters
            //Return 0 (very weak)
        //Else if the string contains only letters and is >8 characters
            //Return 1 (weak)
        //Else if the string contains letters and 1<= number and is 8<= characters
            //Return 2 (strong)
        //Else if the string contains letter, number, and special character and 8<= characters
            //Return 3 (very strong)

    }
    public static String createOutput (String string, int strength){

        /*
         *  Takes in the string and the strength index generated by passwordValidator and generates the complete
         *  output string to satisfy the single output statement requirement.
         */

        //If strength == 0
            // string = "The password 'string' is a very weak password."
        //Else if strength == 1
            // string = "The password 'string' is a weak password."
        //Else if strength == 2
            // string = "The password 'string' is a strong password."
        //Else if strength == 3
            // string = "The password 'string' is a very strong password."
    }
}
